# actual_exp_phase_1
Script para analizar los csv que genera oTree con los datos del de prueba.

actualmente con "otree test experiment --export=bot_data.csv" debe generar los datos

In [1]:
import pandas as pd

In [2]:
all_apps = pd.read_csv('bot_stage_1/all_apps_wide.csv')
payment = pd.read_csv('bot_stage_1/payment.csv')
personal_info = pd.read_csv('bot_stage_1/personal_info.csv')
stage_1 = pd.read_csv('bot_stage_1/stage_1.csv')
stage_2 = pd.read_csv('bot_stage_1/stage_2.csv')

/var/folders/wv/n9lffh7n44scbybpz22gdvh80000gn/T/ipykernel_12388/3628258833.py:1: DtypeWarning: Columns (89,102,115,128,141,154,167,180,193,206,219,232,245,258,271,284,297,310,323,336,349,362,375,388,401,414,427,440,453,466,479,492,505,518,531,544,557,570,583,596,609,622,635,648,661,674,687,700,713,726,739,752,765,778,791,804,817,830,843,856,869,882,895,908,921,934,947,960,973,986,999,1012,1025,1038,1051,1064,1077,1090,1103,1116,1129,1142,1155,1168,1181,1194,1207,1223,1224,1232,1241,1250,1259,1268,1277,1286,1295,1304,1313,1322) have mixed types. Specify dtype option on import or set low_memory=False.
  all_apps = pd.read_csv('bot_stage_1/all_apps_wide.csv')

In [3]:
last_session_code = (
    all_apps
    .sort_values(by='participant.time_started_utc',ascending=False)
    ['session.code']
    .values
    [0]
)

In [4]:
all_apps[all_apps['session.code'] == last_session_code]

,participant.id_in_session,participant.code,participant.label,participant._is_bot,participant._index_in_pages,participant._max_page_index,participant._current_app_name,participant._current_page_name,participant.time_started_utc,participant.visited,...,stage_1.10.subsession.round_number,stage_1.11.player.id_in_group,stage_1.11.player.role,stage_1.11.player.payoff,stage_1.11.player.topic_idx,stage_1.11.player.answer,stage_1.11.player.wtl,stage_1.11.player.min_opp_punish,stage_1.11.group.id_in_subsession,stage_1.11.subsession.round_number
673,1,9zikkunp,NaN,1,855,854,payment,ComputePayoffs,2025-11-16 23:34:24.569140,1,...,10.0,1.0,NaN,0.0,5.0,A,5.0,6.0,1.0,11.0
674,2,39j572uf,NaN,1,855,854,payment,ComputePayoffs,2025-11-16 23:34:24.584188,1,...,10.0,2.0,NaN,0.0,2.0,B,3.0,2.0,1.0,11.0
675,3,e1bfors3,NaN,1,855,854,payment,ComputePayoffs,2025-11-16 23:34:24.589686,1,...,10.0,3.0,NaN,0.0,7.0,B,8.0,6.0,1.0,11.0
676,4,u7y0pqi0,NaN,1,855,854,payment,ComputePayoffs,2025-11-16 23:34:24.595152,1,...,10.0,4.0,NaN,0.0,1.0,A,7.0,8.0,1.0,11.0
677,5,30z925i3,NaN,1,855,854,payment,ComputePayoffs,2025-11-16 23:34:24.600188,1,...,10.0,5.0,NaN,0.0,0.0,B,5.0,4.0,1.0,11.0
678,6,998l2xa3,NaN,1,855,854,payment,ComputePayoffs,2025-11-16 23:34:24.605267,1,...,10.0,6.0,NaN,0.0,6.0,A,9.0,0.0,1.0,11.0
679,7,xcubwv90,NaN,1,855,854,payment,ComputePayoffs,2025-11-16 23:34:24.610358,1,...,10.0,7.0,NaN,0.0,1.0,B,3.0,0.0,1.0,11.0
680,8,imt6s7pm,NaN,1,855,854,payment,ComputePayoffs,2025-11-16 23:34:24.615432,1,...,10.0,8.0,NaN,0.0,0.0,A,4.0,4.0,1.0,11.0
681,9,iqsdo7bi,NaN,1,855,854,payment,ComputePayoffs,2025-11-16 23:34:24.620434,1,...,10.0,9.0,NaN,0.0,2.0,A,2.0,7.0,1.0,11.0
682,10,byy1e2n7,NaN,1,855,854,payment,ComputePayoffs,2025-11-16 23:34:24.625545,1,...,10.0,10.0,NaN,0.0,3.0,B,7.0,7.0,1.0,11.0
683,11,j5ywtbw0,NaN,1,855,854,payment,ComputePayoffs,2025-11-16 23:34:24.630569,1,...,10.0,11.0,NaN,0.0,5.0,B,2.0,6.0,1.0,11.0
684,12,3e2cdsl1,NaN,1,855,854,payment,ComputePayoffs,2025-11-16 23:34:24.635645,1,...,10.0,12.0,NaN,0.0,7.0,B,6.0,8.0,1.0,11.0
685,13,2dj39gc0,NaN,1,855,854,payment,ComputePayoffs,2025-11-16 23:34:24.640539,1,...,10.0,13.0,NaN,0.0,1.0,B,8.0,4.0,1.0,11.0
686,14,lmbgigtx,NaN,1,855,854,payment,ComputePayoffs,2025-11-16 23:34:24.645529,1,...,10.0,14.0,NaN,0.0,0.0,B,6.0,10.0,1.0,11.0
687,15,nburqiwz,NaN,1,855,854,payment,ComputePayoffs,2025-11-16 23:34:24.650546,1,...,10.0,15.0,NaN,0.0,4.0,A,4.0,6.0,1.0,11.0

In [5]:
personal_info[personal_info['session.code'] == last_session_code]

,participant.id_in_session,participant.code,participant.label,participant._is_bot,participant._index_in_pages,participant._max_page_index,participant._current_app_name,participant._current_page_name,participant.time_started_utc,participant.visited,...,player.racial_identification,player.previous_experiment,group.id_in_subsession,subsession.round_number,session.code,session.label,session.mturk_HITId,session.mturk_HITGroupId,session.comment,session.is_demo
0,1,9zikkunp,NaN,1,855,854,payment,ComputePayoffs,2025-11-16 23:34:24.569140,1,...,Pacific Islander,2,1,1,j6qonhcd,NaN,NaN,NaN,NaN,0
1,2,39j572uf,NaN,1,855,854,payment,ComputePayoffs,2025-11-16 23:34:24.584188,1,...,Pacific Islander,2,1,1,j6qonhcd,NaN,NaN,NaN,NaN,0
2,3,e1bfors3,NaN,1,855,854,payment,ComputePayoffs,2025-11-16 23:34:24.589686,1,...,Pacific Islander,2,1,1,j6qonhcd,NaN,NaN,NaN,NaN,0
3,4,u7y0pqi0,NaN,1,855,854,payment,ComputePayoffs,2025-11-16 23:34:24.595152,1,...,Pacific Islander,2,1,1,j6qonhcd,NaN,NaN,NaN,NaN,0
4,5,30z925i3,NaN,1,855,854,payment,ComputePayoffs,2025-11-16 23:34:24.600188,1,...,Pacific Islander,2,1,1,j6qonhcd,NaN,NaN,NaN,NaN,0
5,6,998l2xa3,NaN,1,855,854,payment,ComputePayoffs,2025-11-16 23:34:24.605267,1,...,Pacific Islander,2,1,1,j6qonhcd,NaN,NaN,NaN,NaN,0
6,7,xcubwv90,NaN,1,855,854,payment,ComputePayoffs,2025-11-16 23:34:24.610358,1,...,Pacific Islander,2,1,1,j6qonhcd,NaN,NaN,NaN,NaN,0
7,8,imt6s7pm,NaN,1,855,854,payment,ComputePayoffs,2025-11-16 23:34:24.615432,1,...,Pacific Islander,2,1,1,j6qonhcd,NaN,NaN,NaN,NaN,0
8,9,iqsdo7bi,NaN,1,855,854,payment,ComputePayoffs,2025-11-16 23:34:24.620434,1,...,Pacific Islander,2,1,1,j6qonhcd,NaN,NaN,NaN,NaN,0
9,10,byy1e2n7,NaN,1,855,854,payment,ComputePayoffs,2025-11-16 23:34:24.625545,1,...,Pacific Islander,2,1,1,j6qonhcd,NaN,NaN,NaN,NaN,0
10,11,j5ywtbw0,NaN,1,855,854,payment,ComputePayoffs,2025-11-16 23:34:24.630569,1,...,Pacific Islander,2,1,1,j6qonhcd,NaN,NaN,NaN,NaN,0
11,12,3e2cdsl1,NaN,1,855,854,payment,ComputePayoffs,2025-11-16 23:34:24.635645,1,...,Pacific Islander,2,1,1,j6qonhcd,NaN,NaN,NaN,NaN,0
12,13,2dj39gc0,NaN,1,855,854,payment,ComputePayoffs,2025-11-16 23:34:24.640539,1,...,Pacific Islander,2,1,1,j6qonhcd,NaN,NaN,NaN,NaN,0
13,14,lmbgigtx,NaN,1,855,854,payment,ComputePayoffs,2025-11-16 23:34:24.645529,1,...,Pacific Islander,2,1,1,j6qonhcd,NaN,NaN,NaN,NaN,0
14,15,nburqiwz,NaN,1,855,854,payment,ComputePayoffs,2025-11-16 23:34:24.650546,1,...,Pacific Islander,2,1,1,j6qonhcd,NaN,NaN,NaN,NaN,0

In [6]:
stage_1[stage_1['session.code'] == last_session_code]

,participant.id_in_session,participant.code,participant.label,participant._is_bot,participant._index_in_pages,participant._max_page_index,participant._current_app_name,participant._current_page_name,participant.time_started_utc,participant.visited,...,player.wtl,player.min_opp_punish,group.id_in_subsession,subsession.round_number,session.code,session.label,session.mturk_HITId,session.mturk_HITGroupId,session.comment,session.is_demo
0,1,9zikkunp,NaN,1,855,854,payment,ComputePayoffs,2025-11-16 23:34:24.569140,1,...,10,6,1,1,j6qonhcd,NaN,NaN,NaN,NaN,0
1,2,39j572uf,NaN,1,855,854,payment,ComputePayoffs,2025-11-16 23:34:24.584188,1,...,10,3,1,1,j6qonhcd,NaN,NaN,NaN,NaN,0
2,3,e1bfors3,NaN,1,855,854,payment,ComputePayoffs,2025-11-16 23:34:24.589686,1,...,2,1,1,1,j6qonhcd,NaN,NaN,NaN,NaN,0
3,4,u7y0pqi0,NaN,1,855,854,payment,ComputePayoffs,2025-11-16 23:34:24.595152,1,...,3,6,1,1,j6qonhcd,NaN,NaN,NaN,NaN,0
4,5,30z925i3,NaN,1,855,854,payment,ComputePayoffs,2025-11-16 23:34:24.600188,1,...,3,5,1,1,j6qonhcd,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
160,11,j5ywtbw0,NaN,1,855,854,payment,ComputePayoffs,2025-11-16 23:34:24.630569,1,...,2,6,1,11,j6qonhcd,NaN,NaN,NaN,NaN,0
161,12,3e2cdsl1,NaN,1,855,854,payment,ComputePayoffs,2025-11-16 23:34:24.635645,1,...,6,8,1,11,j6qonhcd,NaN,NaN,NaN,NaN,0
162,13,2dj39gc0,NaN,1,855,854,payment,ComputePayoffs,2025-11-16 23:34:24.640539,1,...,8,4,1,11,j6qonhcd,NaN,NaN,NaN,NaN,0
163,14,lmbgigtx,NaN,1,855,854,payment,ComputePayoffs,2025-11-16 23:34:24.645529,1,...,6,10,1,11,j6qonhcd,NaN,NaN,NaN,NaN,0
164,15,nburqiwz,NaN,1,855,854,payment,ComputePayoffs,2025-11-16 23:34:24.650546,1,...,4,6,1,11,j6qonhcd,NaN,NaN,NaN,NaN,0

In [7]:
stage_2[stage_2['session.code'] == last_session_code]

,participant.id_in_session,participant.code,participant.label,participant._is_bot,participant._index_in_pages,participant._max_page_index,participant._current_app_name,participant._current_page_name,participant.time_started_utc,participant.visited,...,player.expr_A_from_A,player.expr_A_from_B,group.id_in_subsession,subsession.round_number,session.code,session.label,session.mturk_HITId,session.mturk_HITGroupId,session.comment,session.is_demo
56875,1,9zikkunp,NaN,1,855,854,payment,ComputePayoffs,2025-11-16 23:34:24.569140,1,...,2.0,3.0,1,1,j6qonhcd,NaN,NaN,NaN,NaN,0
56876,2,39j572uf,NaN,1,855,854,payment,ComputePayoffs,2025-11-16 23:34:24.584188,1,...,4.0,4.0,1,1,j6qonhcd,NaN,NaN,NaN,NaN,0
56877,3,e1bfors3,NaN,1,855,854,payment,ComputePayoffs,2025-11-16 23:34:24.589686,1,...,5.0,5.0,1,1,j6qonhcd,NaN,NaN,NaN,NaN,0
56878,4,u7y0pqi0,NaN,1,855,854,payment,ComputePayoffs,2025-11-16 23:34:24.595152,1,...,5.0,2.0,1,1,j6qonhcd,NaN,NaN,NaN,NaN,0
56879,5,30z925i3,NaN,1,855,854,payment,ComputePayoffs,2025-11-16 23:34:24.600188,1,...,4.0,1.0,1,1,j6qonhcd,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58235,11,j5ywtbw0,NaN,1,855,854,payment,ComputePayoffs,2025-11-16 23:34:24.630569,1,...,3.0,2.0,1,91,j6qonhcd,NaN,NaN,NaN,NaN,0
58236,12,3e2cdsl1,NaN,1,855,854,payment,ComputePayoffs,2025-11-16 23:34:24.635645,1,...,1.0,0.0,1,91,j6qonhcd,NaN,NaN,NaN,NaN,0
58237,13,2dj39gc0,NaN,1,855,854,payment,ComputePayoffs,2025-11-16 23:34:24.640539,1,...,0.0,3.0,1,91,j6qonhcd,NaN,NaN,NaN,NaN,0
58238,14,lmbgigtx,NaN,1,855,854,payment,ComputePayoffs,2025-11-16 23:34:24.645529,1,...,6.0,3.0,1,91,j6qonhcd,NaN,NaN,NaN,NaN,0
58239,15,nburqiwz,NaN,1,855,854,payment,ComputePayoffs,2025-11-16 23:34:24.650546,1,...,3.0,2.0,1,91,j6qonhcd,NaN,NaN,NaN,NaN,0

In [8]:
# Display relevant columns for stage 2
(
    stage_2
    [stage_2['session.code']==last_session_code]
    [['participant.id_in_session', 'participant.code',
       'participant._is_bot', 'participant._current_app_name',
       'participant.payoff', 'player.payoff',
       'player.id_in_group',
       'player.topic_idx', 'player.treatment_idx',
       'subsession.round_number', 'session.code']]
    .sort_values(by=['subsession.round_number', 'participant.id_in_session'])
)

,participant.id_in_session,participant.code,participant._is_bot,participant._current_app_name,participant.payoff,player.payoff,player.id_in_group,player.topic_idx,player.treatment_idx,subsession.round_number,session.code
56875,1,9zikkunp,1,payment,-3000.0,0.0,1,NaN,NaN,1,j6qonhcd
56876,2,39j572uf,1,payment,-1000.0,0.0,2,NaN,NaN,1,j6qonhcd
56877,3,e1bfors3,1,payment,-1000.0,0.0,3,NaN,NaN,1,j6qonhcd
56878,4,u7y0pqi0,1,payment,-7000.0,0.0,4,NaN,NaN,1,j6qonhcd
56879,5,30z925i3,1,payment,-4000.0,0.0,5,NaN,NaN,1,j6qonhcd
...,...,...,...,...,...,...,...,...,...,...,...
58235,11,j5ywtbw0,1,payment,-9000.0,0.0,11,2.0,7.0,91,j6qonhcd
58236,12,3e2cdsl1,1,payment,-6000.0,0.0,12,6.0,7.0,91,j6qonhcd
58237,13,2dj39gc0,1,payment,-6000.0,0.0,13,3.0,3.0,91,j6qonhcd
58238,14,lmbgigtx,1,payment,-6000.0,0.0,14,4.0,5.0,91,j6qonhcd
58239,15,nburqiwz,1,payment,-7000.0,0.0,15,4.0,2.0,91,j6qonhcd